// Regenerates the committed files in vendor/.
//
// The app is served as plain static files from GitHub Pages, so the third-party
// libraries it needs are bundled here at development time and committed. Run
// `npm install && npm run build:vendor` after bumping a dependency in
// package.json.
import { build } from "esbuild";
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const vendor = path.join(root, "vendor");

fs.mkdirSync(vendor, { recursive: true });

// niimbluelib ships CommonJS only, so bundle it into a browser IIFE exposing the
// `niimbluelib` global. Its Capacitor transport is for native mobile builds and
// pulls in a large dependency tree we never touch, so it is stubbed out.
const capacitorStub = path.join(root, "tools", "capacitor-stub.js");

await build({
  entryPoints: [require.resolve("@mmote/niimbluelib")],
  bundle: true,
  format: "iife",
  globalName: "niimbluelib",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  legalComments: "none",
  alias: {
    "@capacitor/core": capacitorStub,
    "@capacitor-community/bluetooth-le": capacitorStub,
  },
  banner: { js: "/* @mmote/niimbluelib (MIT) - https://github.com/MultiMote/niimbluelib */" },
  outfile: path.join(vendor, "niimbluelib.js"),
});

// pdf.js already ships browser-ready ES modules; copy them verbatim.
const pdfjsBuild = path.dirname(require.resolve("pdfjs-dist/build/pdf.mjs"));
for (const file of ["pdf.min.mjs", "pdf.worker.min.mjs"]) {
  fs.copyFileSync(path.join(pdfjsBuild, file), path.join(vendor, file));
}

const versionOf = (pkg) => require(`${pkg}/package.json`).version;
fs.writeFileSync(
  path.join(vendor, "VERSIONS.txt"),
  [
    "Generated by tools/build-vendor.mjs - do not edit by hand.",
    "",
    `@mmote/niimbluelib  ${versionOf("@mmote/niimbluelib")}  (MIT)  -> niimbluelib.js`,
    `pdfjs-dist          ${versionOf("pdfjs-dist")}  (Apache-2.0)  -> pdf.min.mjs, pdf.worker.min.mjs`,
    "",
  ].join("\n"),
);

for (const f of fs.readdirSync(vendor)) {
  const { size } = fs.statSync(path.join(vendor, f));
  console.log(`${f.padEnd(24)} ${(size / 1024).toFixed(0)} KiB`);
}
